version: '3.2'

# ports : host:container
services:
  traefik:
    image: traefik:v1.7.4-alpine
    command: 
      - --api
      - --docker
      - --docker.domain=mapx.localhost
      - --defaultentrypoints=http
      - "--entryPoints=Name:http Address::80 Compress:true"
    ports:
      - target: 80
        published: 8880
        mode: host
      - target: 8080
        published: 8881
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./_shared/traefik/certs:/certs
  app:
    env_file: mapx.dev.env
    build: ./app/.
    image: docker-hub.unepgrid.ch/mapx/mx-app-shiny:1.6.66-debian
    restart: always
    ports:
      - 3838
    hostname: mx_app
    depends_on:
      - pg
      - traefik
    labels:
      - traefik.s1.frontend.rule=Host:app.mapx.localhost
      - traefik.s1.frontend.headers.customResponseHeaders=CACHE-CONTROL:no-cache
      - traefik.s1.port=3838
      - traefik.s2.frontend.rule=Host:dev.mapx.localhost
      - traefik.s2.frontend.headers.customResponseHeaders=CACHE-CONTROL:no-cache
      - traefik.s2.port=3434
    volumes:
      - ./app:/srv/shiny-server/dev
      - ./_shared:/shared
  api:
    env_file: mapx.dev.env
    build: ./api/.
    image: docker-hub.unepgrid.ch/mapx/mx-api-node:1.6.66-alpine
    restart: always
    ports: 
      - 3030
    hostname: mx_api
    depends_on:
      - pg
      - redis
      - traefik
    labels:
      - traefik.s1.frontend.rule=Host:api.mapx.localhost
      - traefik.s1.port=3030
      - traefik.s2.frontend.rule=Host:apidev.mapx.localhost
      - traefik.s2.port=3333
    volumes:
      - ./api:/apidev
      - ./_shared:/shared
  geoserver :
    env_file: mapx.dev.env
    build: ./geoserver/.
    image: fredmoser/mx-api-geoserver:2.14.1-alpine
    ports: 
      - 8882:8080
    volumes:
      - ./_shared/geoserver:/shared/geoserver
    labels:
      - traefik.frontend.rule=Host:geoserver.mapx.localhost
  pg:
    env_file: mapx.dev.env
    image: mdillon/postgis:10-alpine
    restart: always
    hostname: pg
    volumes:
      - ./_shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pg/init/script_initdb.sh:/docker-entrypoint-initdb.d/script_initdb.sh
      - ./pg/init/sql_files:/docker-entrypoint-initdb.d/sql_files
    ports :
      - 5432:5432
  redis:
    image: redis:alpine
    restart: always
    hostname: redis
    command: redis-server /usr/local/etc/redis/redis.conf 
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379
  probe:
    build: ./probe/.
    image: fredmoser/mx-probe:0.2-go
    labels:
      - traefik.frontend.rule=Host:probe.mapx.localhost
      - traefik.port=8080
    ports:
      - 8080
  wsecho:
    image: jmalloc/echo-server
    labels:
      - traefik.frontend.rule=Host:wsecho.mapx.localhost
      - traefik.port=8080
    ports:
      - 8080
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: none
    labels:
      - traefik.s1.frontend.rule=Host:mail.mapx.localhost
      - traefik.s1.port=8025
